---
exclude_paths:
- '.git/**'
- '.github/**'
- '**.md'
- '**.ps1'
- '.idea/**'
- '.jdi-light-html/**'
- '.jdi-light-html-tests/**'
- '.config/checkstyle/**'
- '.jdi-bdd-tests/**'
- '.jdi-bdd/**'
- '.jdi-eyes-demo/**'
- '.jdi-light-angular-tests-with-mocks/**'
- '.jdi-light-angular-tests/**'
- '.jdi-light-angular/**'
- '.jdi-light-applitools-tests/**'
- '.jdi-light-bootstrap-tests/**'
- '.jdi-light-bootstrap/**'
- '.jdi-light-eyes/**'
- '.jdi-light-html-tests/**'
- '.jdi-light-html/**'
- '.jdi-light-mobile-tests/**'
- '.jdi-light-mobile/**'
- '.jdi-light/**'
- '.test-examples/**'
- '.test-templates/**'
